### ISSUE TITLE
bound/free (1.1.8)

### ISSUE THREAD

**Issue by kimurakoichi** [minghai/sicp-pdf#6]
1.1.8 Local names のところなんですが、原文でも bound だけだったり free だけだったりしていて、
訳文でもそれを反映してか自由、束縛となっているところが何ヶ所かあります。
これは適宜「変数」を補って、自由変数、束縛変数のように書いた方が良いのではないでしょうか?

具体的な修正案はあとで出します。

**Comment by minghai** [comment]
確かに日本語で「変数は自由です。」というのはあまり聞きなれない表現ですよね。
その方針で修正願います。

よろしくお願いいたします。

**Comment by kimurakoichi** [comment]
pull request しました。
ちょっとおかしな差分になっているかもしれませんので必要なら作り直しますが、
fork したgithub 上のリポジトリをfork元と同期させるにはコマンドを叩くしかないんでしょうか?
ローカルのHDDには最新が来てるけどgithub上はcloneしたときのもの+自分の修正という
妙な状態になっているぽいです。

**Comment by minghai** [comment]
ありがとうございます!

こちらでも今回はconflictしているようで、GitHub上ではmergeできないのでCUIでmergeしてくれというメッセージが出ています。

内容ですが、ejsicp.texiの修正が以前と同じくEUCになっていませんでしょうか? patchがとても大きくなっています。ejsicp.texiの修正を外して頂くか、こちらでjsicp.texとejsicp.texのみ修正を反映するのが良いかと思います。

私の経験では私の元のSarabanderさんのrepositoryをwatchの対象にしておくことで、あちらで変更が起きたときにgithub上でmergeをすることができました。(でも今は1つreadme.mdのcommitがmergeされていない状態です。)

私のrepositoryをwatchして頂くと、今後こちらの変更が起こる度にそちらのrepositoryに反映できるのではないかと思います。
後、現在localが最新でgithub上が遅れているようでしたら一度remoteにpushすることで同期できませんでしょうか?
私はgithub社から提供されたWindows用のGUIを使っていますのでそれでリモートとローカル間のsyncができています。しかし通常はgitコマンドでpushしている状態です。

こちらで手動で当てたほうがよろしければ御一報下さい。
よろしくお願いいたします。

**Comment by kimurakoichi** [comment]
では今回の分について手作業で反映していただけますでしょうか。
確かに文字コードがEUC-JPになってました。

リポジトリの作り直しも考えてちょっとやってみます。

**Comment by minghai** [comment]
遅くなってすみません，反映終わりました！

修正対象のファイルですが、次回からejsicp.texのほうはtexiではなく、texのほうでお願いできますか?
分かりにくいですが最後に"i"が付かないほうです。

texiファイル("i"の付く方)はtexinfoファイルですが、texinfoファイルからPerlスクリプトでtexファイルに変更した後に、さらに修正が必要なためもうそちらはメンテしていない状態です。
分かりにくくてすみませんが、よろしくお願いいたします。

以上、ありがとうございました (^_^)

**Comment by kimurakoichi** [comment]
Texinfoではなく、TeXのファイルに対して修正する件了解です。
以後はそのようにします。
個人的にはわりと好きなんですよねw Texinfo。

**Comment by minghai** [comment]
オリジナルでは今でもtexinfoからmakeでPDFまで落とすようになっているので、こちらもそうできれば良いのですが、いかんせん差分が大きくなっています。
その辺りを同期して頂いた上でmakeも通るようにして頂ければ喜んでmergeさせて頂きます:-)

texinfoは私も割と好きなのですがdvipdfmxでの出力がどうしても美しくできませんでした。
texinfo.texの良いものがあるといいのですが、、、
一度、TeXの品質に慣れてしまうとinfoファイルの閲覧は無しです。X-)
